#!/bin/bash

# Build and test metar.
# Run with no arguments to see the available commands.

metarDir="/home/coder/metar"

option=$1

# Make sure we're running inside the docker container.
if [[ -z "${coder_env}" ]]; then
  echo "Run in the docker container not on the host."
  exit
fi

# Make sure we are running in the metar folder.
if [[ ! $(pwd) == "$metarDir" ]]; then
  echo "Run from the metar folder: $metarDir"
  exit
fi

function buildCmd() {
  # Build the release version of metar.

  releaseExe='bin/linux/metar'
  rm $releaseExe
  nim c -d:release --out:$releaseExe metar/metar

  if [[ ! -e $releaseExe ]]; then
    echo "Error creating the release exe: $releaseExe"
  else
    echo "Created: $releaseExe"
  fi

  exit
}

function testCmd() {
  # Test the release version of metar.

  # Run each test file in the test folder.
  for file in tests/test_*.nim; do
    basename=$(basename $file)

    releaseCmd="nim c -f -d:release -d:nimDebugDlOpen --verbosity:0 -d:test --hints:off -r \
      -p:metar --out:bin/tests/$basename $file"
    echo
    echo $releaseCmd
    $releaseCmd
  done

  exit
}

function dotCmd() {
  # Create and show the metar modules dependency graph.

  # Create my.dot file with the contents of metar.dot after stripping
  # out nim modules.
  # --hints:off

  nim genDepend metar/metar.nim

  metarDot=metar/metar.dot
  if [[ -e $metarDot ]]; then
    echo "Created: $metarDot"
  else
    echo "Error creating: $metarDot"
    exit
  fi

  find metar -maxdepth 1 -name \*.nim | sed "s:metar/::" | sed "s:.nim::" >names.txt

  names=names.txt
  if [[ -e $names ]]; then
    echo "Created: $names"
  else
    echo "Error creating: $names"
    exit
  fi

  myDot=my.dot
  python3 python/dotMetar.py names.txt metar/metar.dot > $myDot
  if [[ -e $myDot ]]; then
    echo "Created: $myDot"
  else
    echo "Error creating: $myDot"
    exit
  fi

  svgFile=docs/html/dependencies.svg
  dot -Tsvg $myDot -o $svgFile
  if [[ -e $svgFile ]]; then
    echo "Created: $svgFile"
    echo "Open $svgFile in Firefox."
  else
    echo "Error creating: $svgFile"
    exit
  fi

  rm names.txt
  rm $myDot
  rm metar.deps
  rm metar/metar.dot
  rm metar/metar.png

}

function stfCmd() {
  # Run stf files.
  bin/linux/stfrunner -d stf-files
}

case $option in
  b)
    buildCmd
    ;;
  t)
    testCmd
    ;;
  dot)
    dotCmd
    ;;
  stf)
    stfCmd
    ;;
  *)

cat << EOF
b         Build the release version of metar.
t         Test the release version of metar.
dot       Build the dependency graph.
stf       Run metar stf tests.
EOF
    ;;
esac
