#!/usr/bin/env python

# Run metar using the python interface.

import os
import sys
import argparse

def add_import_path(folder):
  """
  Add the given folder to the python path.
  """
  # Verify metar.so exists and add its folder to the path.
  absolute_path = os.path.abspath(__file__)
  parent_dir = os.path.dirname(os.path.dirname(absolute_path))

  sys.path.insert(0, folder)


# import metar
# import json

def main(args):
  if not os.path.exists(args.folder):
    print "folder does not exist: " + args.folder
    return
  path = os.path.join(args.folder, "metar.so")
  if not os.path.exists(path):
    print("Cannot find metar.so in the folder")
    return

  add_import_path(args.folder)

  import metar
  # Print the metar version number.
  print("The metar version number = %s" % metar.get_version())

  if not os.path.exists(args.filename):
    print("image file not found")
    return

  data = metar.read_metadata(args.filename)
  print data



def parse_command_line():
  """
  Parse the command line and return an object that has the parameters.
  """

  parser = argparse.ArgumentParser(description="""\
Run metar using the python interface.
""")
  parser.add_argument("folder", help="the folder containing metar.so")
  parser.add_argument("filename", help="an image file to analyze")
  args = parser.parse_args()
  return args

if __name__ == "__main__":
  args = parse_command_line()
  main(args)
