#!/usr/bin/env python

# Run metar using the python interface.

import os
import sys
import argparse
import metar
import json

def main(args):
  if not os.path.exists(args.filename):
    print("Image file not found.")
    return
  print(metar.read_metadata(args.filename))


def parse_command_line():
  """
  Parse the command line and return an object that has the parameters.
  """

  parser = argparse.ArgumentParser(description="""\
Show image metadata.
""")
  parser.add_argument("filename", help="an image file to analyze")
  args = parser.parse_args()
  return args

if __name__ == "__main__":
  args = parse_command_line()
  main(args)
